#!/bin/bash

# Get current script path
SCRIPT_PATH="$( dirname -- "$( readlink -f -- "${0}"; )"; )"
# Activate OctoDNS Python venv
source "${SCRIPT_PATH}/common.sh"

SOURCES="$(find *.py octodns_cloudflare tests -name "*.py") $(grep --files-with-matches '^#!.*python' script/* || true)"

isort "$@" $SOURCES
black "$@" $SOURCES
