#!/bin/sh
set -e

cd "$(dirname "$0")/.."

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="env"
fi

ACTIVATE="$VENV_NAME/bin/activate"
if [ ! -f "$ACTIVATE" ]; then
    echo "$ACTIVATE does not exist, run ./script/bootstrap" >&2
    exit 1
fi
. "$ACTIVATE"

export CLOUDFLARE_ACCOUNT_ID=
export CLOUDFLARE_EMAIL=
export CLOUDFLARE_TOKEN=

pytest --disable-network "$@"
