#!/bin/bash

# Get current script path
SCRIPT_PATH="$( dirname -- "$( readlink -f -- "${0}"; )"; )"
# Activate OctoDNS Python venv
source "${SCRIPT_PATH}/common.sh"

export CLOUDFLARE_ACCOUNT_ID=
export CLOUDFLARE_EMAIL=
export CLOUDFLARE_TOKEN=

pytest --disable-network "$@"
